services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cronko
      POSTGRES_PASSWORD: cronko
      POSTGRES_DB: cronko
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: